stages:
  - build

proxy 📦:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        docker build -f docker/Dockerfile.proxy -t $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/proxy:latest -t $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_TAG .
        docker push $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_TAG
      else
        docker build -f docker/Dockerfile.proxy -t $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/proxy:latest .
      fi
    - docker push $CI_REGISTRY_IMAGE/proxy:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/proxy:latest

web 📦:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cp $env_production packages/web/.env.production
  script:
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        docker build -f docker/Dockerfile.web -t $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/web:latest -t $CI_REGISTRY_IMAGE/web:$CI_COMMIT_TAG .
        docker push $CI_REGISTRY_IMAGE/web:$CI_COMMIT_TAG
      else
        docker build -f docker/Dockerfile.web -t $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/web:latest .
      fi
    - docker push $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/web:latest
